### ISSUE TITLE
websocket subscribing to open orders fails

### ISSUE THREAD

**Issue by lk16** [aopoltorzhicky/go_kraken#21]
Hi,

I'm having trouble with subscribing to open orders using the websocket module.

I copied the code from examples/auth/main.go in this repo and added my own keys.

When running it from the shell I got some output telling me connecting and subscribing to my own open orders succeeded.
```
2020/12/12 21:49:10 [WARN]: invalid data length: []interface {}{[]interface {}{
*** snip many go-objects with info of requests from the past ***
}}, "openOrders", map[string]interface {}{"sequence":1}}
```

As expected with these kind of errors, I don't receive any mesage on the channel returned by Listen().

It seems the data length is 3 and not 4 as the library [expects](https://github.com/aopoltorzhicky/go_kraken/blob/master/websocket/messages.go#L82).

Can you reproduce this on your end? Should I make a PR with a fix?

Regards,
lk16

**Comment by aopoltorzhicky** [comment]
Hi,

Thanks for the issue and PR. I'll merge it as soon as possible.
