### ISSUE TITLE
1 commit behind on latest tag/release

### ISSUE THREAD

**Issue by r1se** [aopoltorzhicky/go_kraken#23]
Hello.
Your release v0.10.0 is 1 commit behind from master, so when people use go.mod, he get broken version without [fix](https://github.com/aopoltorzhicky/go_kraken/commit/5fae33b603848170da4ea86c0db14fb2c583dc5e)

**Comment by r1se** [comment]
Easy fix, use
go get github.com/aopoltorzhicky/go_kraken/websocket@master

**Comment by aopoltorzhicky** [comment]
Thanks for pull request and the issue. I published v0.0.11 with your changes and previous fixes.

**Comment by byroncoetsee** [comment]
Sorry to bring this up from the dead but, I'm seeing code in this repo that I can't find in my own version of this package... I've used the standard `go get`. I've also tried `go get github.com/aopoltorzhicky/go_kraken/websocket@master` but no luck.

According to my `go.mod` file, I'm using v0.0.3 but it seems the latest is v0.0.5? Or v0.0.4? Or v0.1.10? I'm not sure - I get different numbers depending where I look...

**Comment by aopoltorzhicky** [comment]
> Sorry to bring this up from the dead but, I'm seeing code in this repo that I can't find in my own version of this package... I've used the standard `go get`. I've also tried `go get github.com/aopoltorzhicky/go_kraken/websocket@master` but no luck.
> 
> According to my `go.mod` file, I'm using v0.0.3 but it seems the latest is v0.0.5? Or v0.0.4? Or v0.1.10? I'm not sure - I get different numbers depending where I look...


Hello! 
The current version is websocket/v0.1.10. It is not compatible with versions 0.0.x because the kernel of library has been rewritten. An old version of the library may have been cached. You could try something like that:

```bash
go get -u go get github.com/aopoltorzhicky/go_kraken/websocket@v0.1.10
```

**Comment by byroncoetsee** [comment]
Ok I deleted what I had and ran `go get -u github.com/aopoltorzhicky/go_kraken/websocket@v0.1.10`
My go.mod now includes these which I assume are correct.
It must have been a caching issue - which is strange since the last release was made ages ago 🤔
Anyway. Thank you, again 😊 

```
github.com/aopoltorzhicky/go_kraken/rest v0.0.4 // indirect
github.com/aopoltorzhicky/go_kraken/websocket v0.1.10 // indirect
```
