### ISSUE TITLE
Can't parse open order websocket messages 

### ISSUE THREAD

**Issue by ronkeiser** [aopoltorzhicky/go_kraken#27]
Thank you very much for your work on this library. 

I'm currently getting a "Can't parse data" error when receiving incoming websocket messages regarding open orders (listening for `DataUpdates` from `AuthClient.SubscribeOpenOrders`).

I believe the type assertion `data.([]interface{})`  is failing. I'm not sure if Kraken changed the message format recently?

**Comment by aopoltorzhicky** [comment]
Thank you for issue! I fixed it in new [release](https://github.com/aopoltorzhicky/go_kraken/releases/tag/websocket%2Fv0.0.12). You can found commit [here](https://github.com/aopoltorzhicky/go_kraken/commit/a4f8e9aae9303d35bfa122bbff0a0996d4a36943)
