### ISSUE TITLE
`resubscribe()` returns without exhausting all private subscribes

### ISSUE THREAD

**Issue by gadfly16** [aopoltorzhicky/go_kraken#54]
In case of private channels `resubscribe()` returns the `subscribeToPrivate` functions return value without checking its value, exiting the function and thus the for loop in case of a successfull subscription too. If both channels is subscribed for **only one of them will resubscribe**.

It should check the error value and only return if the err is not `nil`, like `default:`.

**Comment by aopoltorzhicky** [comment]
Thanks for the issue. It was fixed in #55.
