### ISSUE TITLE
Great job! :)

### ISSUE THREAD

**Issue by eljefejames** [aopoltorzhicky/go_kraken#9]
Thanks for this -  looks very smooth. Heads up - I noticed that running the basic orderbook example gives an 'Unknown message type:'  error inside client.handleChannel.  Maybe I'm missing something?

**Comment by aopoltorzhicky** [comment]
Good day! Thanx for issue. I think it's due to update Websocket API version on Kraken. I'll fix this soon.

**Comment by aopoltorzhicky** [comment]
@eljefejames I fixed. Can you check it?

**Comment by eljefejames** [comment]
@aopoltorzhicky  - this works perfectly now, thanks!
